---
framework: mocha
preRun:
     command:
        - npm install
        - npm install mongodb
        - mongo --version
        - mkdir -p data/db
        - mongod --dbpath=data/db > /dev/null 2>&1 &
        - sleep 3
        - npm run pretest
preMerge:
  pattern:
    - "./test/*.js"
postMerge:
  pattern:
    - "./test/*.js"
postRun:
     command:
        - node --version
configFile: mocharc.yml
version: 1.0
